# Generated by Django 5.1 on 2024-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn_item_id', models.PositiveBigIntegerField(db_index=True)),
                ('deleted', models.BooleanField()),
                ('item_type', models.CharField(max_length=20)),
                ('item_by', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField()),
                ('item_content', models.TextField()),
                ('parent', models.PositiveBigIntegerField()),
                ('kids', models.JSONField()),
                ('item_url', models.TextField()),
                ('item_score', models.IntegerField()),
                ('category_id', models.PositiveBigIntegerField()),
                ('item_title', models.TextField()),
                ('descendants', models.PositiveBigIntegerField()),
                ('label', models.CharField(max_length=20)),
                ('item_status', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
