# Generated by Django 5.1 on 2024-10-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hnitem',
            table='hn_item',
        ),
    ]
