# Generated by Django 5.1 on 2024-10-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hnitem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnitem',
            name='hn_item_id',
            field=models.PositiveBigIntegerField(db_index=True, unique=True),
        ),
    ]
