# Generated by Django 5.1 on 2024-10-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hnitem_hn_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnitem',
            name='deleted',
            field=models.BooleanField(null=True),
        ),
    ]
