# Generated by Django 5.1 on 2024-10-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hnitem_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnitem',
            name='category_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
