# Generated by Django 5.1 on 2024-10-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_hnitem_category_id_alter_hnitem_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnitem',
            name='descendants',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='item_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='item_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='item_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='item_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='item_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='item_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='kids',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='label',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hnitem',
            name='parent',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
