ENDPOINT_USER = "user"
ENDPOINT_ITEM = "item"
ENDPOINT_TOPSTORIES = "topstories"
ENDPOINT_NEWESTSTORIES = "newstories"
ENDPOINT_BESTSTORIES = "beststories"
ENDPOINT_ASKSTORIES = "askstories"
ENDPOINT_JOBSTORIES = "jobstories"
ENDPOINT_MAXITEM = "maxitem"
ENDPOINT_UPDATES = "updates"

ITEM_STATUS_NEW = 0
ITEM_STATUS_PROCESS_TITLE = 1
ITEM_STATUS_PROCESS_CATEGORY = 2
ITEM_STATUS_DELETE = 7

ITEM_CATEGORY_DEFAULT = 0
